[versions]

android-targetSdk="37"
android-compileSdk="37"
android-minSdk="24"

agp = "9.2.1"
kotlin = "2.4.0"
composeMultiplatform = "1.11.1"

androidx-appcompat = "1.7.1"
androidx-activity = "1.13.0"
androidx-core = "1.19.0"

icons = "1.7.8"

[libraries]

androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }

material-icons-core = { module = "androidx.compose.material:material-icons-core", version.ref = "icons" }

[plugins]

# Multiplatform
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

# Android
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidMultiplatformLibrary = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }

# JVM
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }